package org.buv.ncloud.common.model;

public enum MessageType {
    LIST_MESSAGE,
    FILE_REQUEST,
    FILE_MESSAGE,
    UPDATE_SERVER_VIEW,
    DELETE_REQUEST,
    MOVE_REQUEST,
    BLOCK_BUTTON,
    CREATE_DIRECTORY,
    AUTHENTICATION,
    AUTH_ERROR,
    ADD_NEW_USER,
    ACCEPT_USER,
    USER_EXIST_ERROR,
    DELETE_USER,
    CUT_REQUEST,
    PASTE_REQUEST,
    PROGRESS_RESET



}
